---
## Add state about the existence of apache2
- name: Check if apache2 is installed
  stat: path=/etc/apache2/apache2.conf
  register: apache2
  tags: php7

- name: Install apache2 extensions
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - libapache2-mod-php7.2
  when: apache2.stat.exists
  notify:
    - reload apache
  tags: php7

- name: Configure - apache2 php.ini
  replace:
    dest=/etc/php/7.2/apache2/php.ini
    regexp="{{ item.regexp }}"
    replace="{{ item.replace }}"
    backup=yes
  with_items:
    - { regexp: 'memory_limit = 128M', replace: 'memory_limit = 512M' }
    - { regexp: ';date.timezone =', replace: 'date.timezone = Europe/Copenhagen' }
    - { regexp: 'upload_max_filesize = 2M', replace: 'upload_max_filesize = 16M' }
    - { regexp: 'post_max_size = 8M', replace: 'post_max_size = 20M' }
    - { regexp: ';realpath_cache_size = 16k', replace: 'realpath_cache_size = 256k' }
    - { regexp: '^short_open_tag =$', replace: 'short_open_tag = Off' }
  when: apache2.stat.exists
  notify:
    - reload apache
  tags: php7

- name: Enable php apache module
  apache2_module: state=present name={{ item }}
  with_items:
    - php7.2
  when: apache2.stat.exists
  notify:
    - reload apache
  tags: php7
